version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres.local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_setup:/docker-entrypoint-initdb.d

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres
    links:
      - postgres
    command:
      --url jdbc:postgresql://postgres:5432/db
      --changeLogFile db.changelog-root.yaml
      --username postgres
      --password password
      update
    volumes:
      - ./changelog:/liquibase/changelog
